package com.relteq.sirius.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Nov 14 14:25:09 PST 2012]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to DownstreamBoundaryCapacityProfiles
 */
public abstract class BaseDownstreamBoundaryCapacityProfiles extends com.relteq.sirius.db.BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1352931909099L;

    /** The Peer class */
    private static final DownstreamBoundaryCapacityProfilesPeer peer =
        new DownstreamBoundaryCapacityProfilesPeer();


    /** The value for the id field */
    private Long id;

    /** The value for the downstreamBoundaryCapacityProfileSetId field */
    private Long downstreamBoundaryCapacityProfileSetId;

    /** The value for the linkId field */
    private Long linkId;

    /** The value for the dt field */
    private BigDecimal dt;

    /** The value for the startTime field */
    private BigDecimal startTime;

    /** The value for the created field */
    private Date created;

    /** The value for the modified field */
    private Date modified;

    /** The value for the createdBy field */
    private String createdBy;

    /** The value for the modifiedBy field */
    private String modifiedBy;

    /** The value for the modstamp field */
    private Date modstamp;


    /**
     * Get the Id
     *
     * @return Long
     */
    public Long getId()
    {
        return id;
    }


    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(Long v) throws TorqueException
    {

        if (!ObjectUtils.equals(this.id, v))
        {
            this.id = v;
            setModified(true);
        }



        // update associated DownstreamBoundaryCapacities
        if (collDownstreamBoundaryCapacitiess != null)
        {
            for (int i = 0; i < collDownstreamBoundaryCapacitiess.size(); i++)
            {
                ((DownstreamBoundaryCapacities) collDownstreamBoundaryCapacitiess.get(i))
                        .setDownstreamBoundaryCapacityProfileId(v);
            }
        }
    }

    /**
     * Get the DownstreamBoundaryCapacityProfileSetId
     *
     * @return Long
     */
    public Long getDownstreamBoundaryCapacityProfileSetId()
    {
        return downstreamBoundaryCapacityProfileSetId;
    }


    /**
     * Set the value of DownstreamBoundaryCapacityProfileSetId
     *
     * @param v new value
     */
    public void setDownstreamBoundaryCapacityProfileSetId(Long v) throws TorqueException
    {

        if (!ObjectUtils.equals(this.downstreamBoundaryCapacityProfileSetId, v))
        {
            this.downstreamBoundaryCapacityProfileSetId = v;
            setModified(true);
        }


        if (aDownstreamBoundaryCapacityProfileSets != null && !ObjectUtils.equals(aDownstreamBoundaryCapacityProfileSets.getId(), v))
        {
            aDownstreamBoundaryCapacityProfileSets = null;
        }

    }

    /**
     * Get the LinkId
     *
     * @return Long
     */
    public Long getLinkId()
    {
        return linkId;
    }


    /**
     * Set the value of LinkId
     *
     * @param v new value
     */
    public void setLinkId(Long v) throws TorqueException
    {

        if (!ObjectUtils.equals(this.linkId, v))
        {
            this.linkId = v;
            setModified(true);
        }


        if (aLinkFamilies != null && !ObjectUtils.equals(aLinkFamilies.getId(), v))
        {
            aLinkFamilies = null;
        }

    }

    /**
     * Get the Dt
     *
     * @return BigDecimal
     */
    public BigDecimal getDt()
    {
        return dt;
    }


    /**
     * Set the value of Dt
     *
     * @param v new value
     */
    public void setDt(BigDecimal v) 
    {

        if (!ObjectUtils.equals(this.dt, v))
        {
            this.dt = v;
            setModified(true);
        }


    }

    /**
     * Get the StartTime
     *
     * @return BigDecimal
     */
    public BigDecimal getStartTime()
    {
        return startTime;
    }


    /**
     * Set the value of StartTime
     *
     * @param v new value
     */
    public void setStartTime(BigDecimal v) 
    {

        if (!ObjectUtils.equals(this.startTime, v))
        {
            this.startTime = v;
            setModified(true);
        }


    }

    /**
     * Get the Created
     *
     * @return Date
     */
    public Date getCreated()
    {
        return created;
    }


    /**
     * Set the value of Created
     *
     * @param v new value
     */
    public void setCreated(Date v) 
    {

        if (!ObjectUtils.equals(this.created, v))
        {
            this.created = v;
            setModified(true);
        }


    }

    /**
     * Get the Modified
     *
     * @return Date
     */
    public Date getModified()
    {
        return modified;
    }


    /**
     * Set the value of Modified
     *
     * @param v new value
     */
    public void setModified(Date v) 
    {

        if (!ObjectUtils.equals(this.modified, v))
        {
            this.modified = v;
            setModified(true);
        }


    }

    /**
     * Get the CreatedBy
     *
     * @return String
     */
    public String getCreatedBy()
    {
        return createdBy;
    }


    /**
     * Set the value of CreatedBy
     *
     * @param v new value
     */
    public void setCreatedBy(String v) 
    {

        if (!ObjectUtils.equals(this.createdBy, v))
        {
            this.createdBy = v;
            setModified(true);
        }


    }

    /**
     * Get the ModifiedBy
     *
     * @return String
     */
    public String getModifiedBy()
    {
        return modifiedBy;
    }


    /**
     * Set the value of ModifiedBy
     *
     * @param v new value
     */
    public void setModifiedBy(String v) 
    {

        if (!ObjectUtils.equals(this.modifiedBy, v))
        {
            this.modifiedBy = v;
            setModified(true);
        }


    }

    /**
     * Get the Modstamp
     *
     * @return Date
     */
    public Date getModstamp()
    {
        return modstamp;
    }


    /**
     * Set the value of Modstamp
     *
     * @param v new value
     */
    public void setModstamp(Date v) 
    {

        if (!ObjectUtils.equals(this.modstamp, v))
        {
            this.modstamp = v;
            setModified(true);
        }


    }

    



    private DownstreamBoundaryCapacityProfileSets aDownstreamBoundaryCapacityProfileSets;

    /**
     * Declares an association between this object and a DownstreamBoundaryCapacityProfileSets object
     *
     * @param v DownstreamBoundaryCapacityProfileSets
     * @throws TorqueException
     */
    public void setDownstreamBoundaryCapacityProfileSets(DownstreamBoundaryCapacityProfileSets v) throws TorqueException
    {
        if (v == null)
        {
            setDownstreamBoundaryCapacityProfileSetId((Long) null);
        }
        else
        {
            setDownstreamBoundaryCapacityProfileSetId(v.getId());
        }
        aDownstreamBoundaryCapacityProfileSets = v;
    }


    /**
     * Returns the associated DownstreamBoundaryCapacityProfileSets object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated DownstreamBoundaryCapacityProfileSets object
     * @throws TorqueException
     */
    public DownstreamBoundaryCapacityProfileSets getDownstreamBoundaryCapacityProfileSets()
        throws TorqueException
    {
        if (aDownstreamBoundaryCapacityProfileSets == null && (!ObjectUtils.equals(this.downstreamBoundaryCapacityProfileSetId, null)))
        {
            aDownstreamBoundaryCapacityProfileSets = DownstreamBoundaryCapacityProfileSetsPeer.retrieveByPK(SimpleKey.keyFor(this.downstreamBoundaryCapacityProfileSetId));
        }
        return aDownstreamBoundaryCapacityProfileSets;
    }

    /**
     * Return the associated DownstreamBoundaryCapacityProfileSets object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated DownstreamBoundaryCapacityProfileSets object
     * @throws TorqueException
     */
    public DownstreamBoundaryCapacityProfileSets getDownstreamBoundaryCapacityProfileSets(Connection connection)
        throws TorqueException
    {
        if (aDownstreamBoundaryCapacityProfileSets == null && (!ObjectUtils.equals(this.downstreamBoundaryCapacityProfileSetId, null)))
        {
            aDownstreamBoundaryCapacityProfileSets = DownstreamBoundaryCapacityProfileSetsPeer.retrieveByPK(SimpleKey.keyFor(this.downstreamBoundaryCapacityProfileSetId), connection);
        }
        return aDownstreamBoundaryCapacityProfileSets;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setDownstreamBoundaryCapacityProfileSetsKey(ObjectKey key) throws TorqueException
    {

        setDownstreamBoundaryCapacityProfileSetId(new Long(((NumberKey) key).longValue()));
    }




    private LinkFamilies aLinkFamilies;

    /**
     * Declares an association between this object and a LinkFamilies object
     *
     * @param v LinkFamilies
     * @throws TorqueException
     */
    public void setLinkFamilies(LinkFamilies v) throws TorqueException
    {
        if (v == null)
        {
            setLinkId((Long) null);
        }
        else
        {
            setLinkId(v.getId());
        }
        aLinkFamilies = v;
    }


    /**
     * Returns the associated LinkFamilies object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated LinkFamilies object
     * @throws TorqueException
     */
    public LinkFamilies getLinkFamilies()
        throws TorqueException
    {
        if (aLinkFamilies == null && (!ObjectUtils.equals(this.linkId, null)))
        {
            aLinkFamilies = LinkFamiliesPeer.retrieveByPK(SimpleKey.keyFor(this.linkId));
        }
        return aLinkFamilies;
    }

    /**
     * Return the associated LinkFamilies object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated LinkFamilies object
     * @throws TorqueException
     */
    public LinkFamilies getLinkFamilies(Connection connection)
        throws TorqueException
    {
        if (aLinkFamilies == null && (!ObjectUtils.equals(this.linkId, null)))
        {
            aLinkFamilies = LinkFamiliesPeer.retrieveByPK(SimpleKey.keyFor(this.linkId), connection);
        }
        return aLinkFamilies;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setLinkFamiliesKey(ObjectKey key) throws TorqueException
    {

        setLinkId(new Long(((NumberKey) key).longValue()));
    }
   


    /**
     * Collection to store aggregation of collDownstreamBoundaryCapacitiess
     */
    protected List collDownstreamBoundaryCapacitiess;

    /**
     * Temporary storage of collDownstreamBoundaryCapacitiess to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initDownstreamBoundaryCapacitiess()
    {
        if (collDownstreamBoundaryCapacitiess == null)
        {
            collDownstreamBoundaryCapacitiess = new ArrayList();
        }
    }


    /**
     * Method called to associate a DownstreamBoundaryCapacities object to this object
     * through the DownstreamBoundaryCapacities foreign key attribute
     *
     * @param l DownstreamBoundaryCapacities
     * @throws TorqueException
     */
    public void addDownstreamBoundaryCapacities(DownstreamBoundaryCapacities l) throws TorqueException
    {
        getDownstreamBoundaryCapacitiess().add(l);
        l.setDownstreamBoundaryCapacityProfiles((DownstreamBoundaryCapacityProfiles) this);
    }

    /**
     * Method called to associate a DownstreamBoundaryCapacities object to this object
     * through the DownstreamBoundaryCapacities foreign key attribute using connection.
     *
     * @param l DownstreamBoundaryCapacities
     * @throws TorqueException
     */
    public void addDownstreamBoundaryCapacities(DownstreamBoundaryCapacities l, Connection con) throws TorqueException
    {
        getDownstreamBoundaryCapacitiess(con).add(l);
        l.setDownstreamBoundaryCapacityProfiles((DownstreamBoundaryCapacityProfiles) this);
    }

    /**
     * The criteria used to select the current contents of collDownstreamBoundaryCapacitiess
     */
    private Criteria lastDownstreamBoundaryCapacitiessCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getDownstreamBoundaryCapacitiess(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List getDownstreamBoundaryCapacitiess()
        throws TorqueException
    {
        if (collDownstreamBoundaryCapacitiess == null)
        {
            collDownstreamBoundaryCapacitiess = getDownstreamBoundaryCapacitiess(new Criteria(10));
        }
        return collDownstreamBoundaryCapacitiess;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this DownstreamBoundaryCapacityProfiles has previously
     * been saved, it will retrieve related DownstreamBoundaryCapacitiess from storage.
     * If this DownstreamBoundaryCapacityProfiles is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getDownstreamBoundaryCapacitiess(Criteria criteria) throws TorqueException
    {
        if (collDownstreamBoundaryCapacitiess == null)
        {
            if (isNew())
            {
               collDownstreamBoundaryCapacitiess = new ArrayList();
            }
            else
            {
                criteria.add(DownstreamBoundaryCapacitiesPeer.DOWNSTREAM_BOUNDARY_CAPACITY_PROFILE_ID, getId() );
                collDownstreamBoundaryCapacitiess = DownstreamBoundaryCapacitiesPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(DownstreamBoundaryCapacitiesPeer.DOWNSTREAM_BOUNDARY_CAPACITY_PROFILE_ID, getId());
                if (!lastDownstreamBoundaryCapacitiessCriteria.equals(criteria))
                {
                    collDownstreamBoundaryCapacitiess = DownstreamBoundaryCapacitiesPeer.doSelect(criteria);
                }
            }
        }
        lastDownstreamBoundaryCapacitiessCriteria = criteria;

        return collDownstreamBoundaryCapacitiess;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getDownstreamBoundaryCapacitiess(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getDownstreamBoundaryCapacitiess(Connection con) throws TorqueException
    {
        if (collDownstreamBoundaryCapacitiess == null)
        {
            collDownstreamBoundaryCapacitiess = getDownstreamBoundaryCapacitiess(new Criteria(10), con);
        }
        return collDownstreamBoundaryCapacitiess;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this DownstreamBoundaryCapacityProfiles has previously
     * been saved, it will retrieve related DownstreamBoundaryCapacitiess from storage.
     * If this DownstreamBoundaryCapacityProfiles is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getDownstreamBoundaryCapacitiess(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collDownstreamBoundaryCapacitiess == null)
        {
            if (isNew())
            {
               collDownstreamBoundaryCapacitiess = new ArrayList();
            }
            else
            {
                 criteria.add(DownstreamBoundaryCapacitiesPeer.DOWNSTREAM_BOUNDARY_CAPACITY_PROFILE_ID, getId());
                 collDownstreamBoundaryCapacitiess = DownstreamBoundaryCapacitiesPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(DownstreamBoundaryCapacitiesPeer.DOWNSTREAM_BOUNDARY_CAPACITY_PROFILE_ID, getId());
                 if (!lastDownstreamBoundaryCapacitiessCriteria.equals(criteria))
                 {
                     collDownstreamBoundaryCapacitiess = DownstreamBoundaryCapacitiesPeer.doSelect(criteria, con);
                 }
             }
         }
         lastDownstreamBoundaryCapacitiessCriteria = criteria;

         return collDownstreamBoundaryCapacitiess;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this DownstreamBoundaryCapacityProfiles is new, it will return
     * an empty collection; or if this DownstreamBoundaryCapacityProfiles has previously
     * been saved, it will retrieve related DownstreamBoundaryCapacitiess from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in DownstreamBoundaryCapacityProfiles.
     */
    protected List getDownstreamBoundaryCapacitiessJoinDownstreamBoundaryCapacityProfiles(Criteria criteria)
        throws TorqueException
    {
        if (collDownstreamBoundaryCapacitiess == null)
        {
            if (isNew())
            {
               collDownstreamBoundaryCapacitiess = new ArrayList();
            }
            else
            {
                criteria.add(DownstreamBoundaryCapacitiesPeer.DOWNSTREAM_BOUNDARY_CAPACITY_PROFILE_ID, getId());
                collDownstreamBoundaryCapacitiess = DownstreamBoundaryCapacitiesPeer.doSelectJoinDownstreamBoundaryCapacityProfiles(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(DownstreamBoundaryCapacitiesPeer.DOWNSTREAM_BOUNDARY_CAPACITY_PROFILE_ID, getId());
            if (!lastDownstreamBoundaryCapacitiessCriteria.equals(criteria))
            {
                collDownstreamBoundaryCapacitiess = DownstreamBoundaryCapacitiesPeer.doSelectJoinDownstreamBoundaryCapacityProfiles(criteria);
            }
        }
        lastDownstreamBoundaryCapacitiessCriteria = criteria;

        return collDownstreamBoundaryCapacitiess;
    }



        
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
            fieldNames.add("Id");
            fieldNames.add("DownstreamBoundaryCapacityProfileSetId");
            fieldNames.add("LinkId");
            fieldNames.add("Dt");
            fieldNames.add("StartTime");
            fieldNames.add("Created");
            fieldNames.add("Modified");
            fieldNames.add("CreatedBy");
            fieldNames.add("ModifiedBy");
            fieldNames.add("Modstamp");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("Id"))
        {
            return getId();
        }
        if (name.equals("DownstreamBoundaryCapacityProfileSetId"))
        {
            return getDownstreamBoundaryCapacityProfileSetId();
        }
        if (name.equals("LinkId"))
        {
            return getLinkId();
        }
        if (name.equals("Dt"))
        {
            return getDt();
        }
        if (name.equals("StartTime"))
        {
            return getStartTime();
        }
        if (name.equals("Created"))
        {
            return getCreated();
        }
        if (name.equals("Modified"))
        {
            return getModified();
        }
        if (name.equals("CreatedBy"))
        {
            return getCreatedBy();
        }
        if (name.equals("ModifiedBy"))
        {
            return getModifiedBy();
        }
        if (name.equals("Modstamp"))
        {
            return getModstamp();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("Id"))
        {
            // Object fields can be null
            if (value != null && ! Long.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setId((Long) value);
            return true;
        }
        if (name.equals("DownstreamBoundaryCapacityProfileSetId"))
        {
            // Object fields can be null
            if (value != null && ! Long.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setDownstreamBoundaryCapacityProfileSetId((Long) value);
            return true;
        }
        if (name.equals("LinkId"))
        {
            // Object fields can be null
            if (value != null && ! Long.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setLinkId((Long) value);
            return true;
        }
        if (name.equals("Dt"))
        {
            // Object fields can be null
            if (value != null && ! BigDecimal.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setDt((BigDecimal) value);
            return true;
        }
        if (name.equals("StartTime"))
        {
            // Object fields can be null
            if (value != null && ! BigDecimal.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setStartTime((BigDecimal) value);
            return true;
        }
        if (name.equals("Created"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setCreated((Date) value);
            return true;
        }
        if (name.equals("Modified"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setModified((Date) value);
            return true;
        }
        if (name.equals("CreatedBy"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setCreatedBy((String) value);
            return true;
        }
        if (name.equals("ModifiedBy"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setModifiedBy((String) value);
            return true;
        }
        if (name.equals("Modstamp"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setModstamp((Date) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(DownstreamBoundaryCapacityProfilesPeer.ID))
        {
            return getId();
        }
        if (name.equals(DownstreamBoundaryCapacityProfilesPeer.DOWNSTREAM_BOUNDARY_CAPACITY_PROFILE_SET_ID))
        {
            return getDownstreamBoundaryCapacityProfileSetId();
        }
        if (name.equals(DownstreamBoundaryCapacityProfilesPeer.LINK_ID))
        {
            return getLinkId();
        }
        if (name.equals(DownstreamBoundaryCapacityProfilesPeer.DT))
        {
            return getDt();
        }
        if (name.equals(DownstreamBoundaryCapacityProfilesPeer.START_TIME))
        {
            return getStartTime();
        }
        if (name.equals(DownstreamBoundaryCapacityProfilesPeer.CREATED))
        {
            return getCreated();
        }
        if (name.equals(DownstreamBoundaryCapacityProfilesPeer.MODIFIED))
        {
            return getModified();
        }
        if (name.equals(DownstreamBoundaryCapacityProfilesPeer.CREATED_BY))
        {
            return getCreatedBy();
        }
        if (name.equals(DownstreamBoundaryCapacityProfilesPeer.MODIFIED_BY))
        {
            return getModifiedBy();
        }
        if (name.equals(DownstreamBoundaryCapacityProfilesPeer.MODSTAMP))
        {
            return getModstamp();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (DownstreamBoundaryCapacityProfilesPeer.ID.equals(name))
        {
            return setByName("Id", value);
        }
      if (DownstreamBoundaryCapacityProfilesPeer.DOWNSTREAM_BOUNDARY_CAPACITY_PROFILE_SET_ID.equals(name))
        {
            return setByName("DownstreamBoundaryCapacityProfileSetId", value);
        }
      if (DownstreamBoundaryCapacityProfilesPeer.LINK_ID.equals(name))
        {
            return setByName("LinkId", value);
        }
      if (DownstreamBoundaryCapacityProfilesPeer.DT.equals(name))
        {
            return setByName("Dt", value);
        }
      if (DownstreamBoundaryCapacityProfilesPeer.START_TIME.equals(name))
        {
            return setByName("StartTime", value);
        }
      if (DownstreamBoundaryCapacityProfilesPeer.CREATED.equals(name))
        {
            return setByName("Created", value);
        }
      if (DownstreamBoundaryCapacityProfilesPeer.MODIFIED.equals(name))
        {
            return setByName("Modified", value);
        }
      if (DownstreamBoundaryCapacityProfilesPeer.CREATED_BY.equals(name))
        {
            return setByName("CreatedBy", value);
        }
      if (DownstreamBoundaryCapacityProfilesPeer.MODIFIED_BY.equals(name))
        {
            return setByName("ModifiedBy", value);
        }
      if (DownstreamBoundaryCapacityProfilesPeer.MODSTAMP.equals(name))
        {
            return setByName("Modstamp", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return getId();
        }
        if (pos == 1)
        {
            return getDownstreamBoundaryCapacityProfileSetId();
        }
        if (pos == 2)
        {
            return getLinkId();
        }
        if (pos == 3)
        {
            return getDt();
        }
        if (pos == 4)
        {
            return getStartTime();
        }
        if (pos == 5)
        {
            return getCreated();
        }
        if (pos == 6)
        {
            return getModified();
        }
        if (pos == 7)
        {
            return getCreatedBy();
        }
        if (pos == 8)
        {
            return getModifiedBy();
        }
        if (pos == 9)
        {
            return getModstamp();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("Id", value);
        }
    if (position == 1)
        {
            return setByName("DownstreamBoundaryCapacityProfileSetId", value);
        }
    if (position == 2)
        {
            return setByName("LinkId", value);
        }
    if (position == 3)
        {
            return setByName("Dt", value);
        }
    if (position == 4)
        {
            return setByName("StartTime", value);
        }
    if (position == 5)
        {
            return setByName("Created", value);
        }
    if (position == 6)
        {
            return setByName("Modified", value);
        }
    if (position == 7)
        {
            return setByName("CreatedBy", value);
        }
    if (position == 8)
        {
            return setByName("ModifiedBy", value);
        }
    if (position == 9)
        {
            return setByName("Modstamp", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(DownstreamBoundaryCapacityProfilesPeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    DownstreamBoundaryCapacityProfilesPeer.doInsert((DownstreamBoundaryCapacityProfiles) this, con);
                    setNew(false);
                }
                else
                {
                    DownstreamBoundaryCapacityProfilesPeer.doUpdate((DownstreamBoundaryCapacityProfiles) this, con);
                }
            }


            if (collDownstreamBoundaryCapacitiess != null)
            {
                for (int i = 0; i < collDownstreamBoundaryCapacitiess.size(); i++)
                {
                    ((DownstreamBoundaryCapacities) collDownstreamBoundaryCapacitiess.get(i)).save(con);
                }
            }
            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
        setId(new Long(((NumberKey) key).longValue()));
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
        setId(new Long(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getId());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public DownstreamBoundaryCapacityProfiles copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public DownstreamBoundaryCapacityProfiles copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public DownstreamBoundaryCapacityProfiles copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new DownstreamBoundaryCapacityProfiles(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public DownstreamBoundaryCapacityProfiles copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new DownstreamBoundaryCapacityProfiles(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected DownstreamBoundaryCapacityProfiles copyInto(DownstreamBoundaryCapacityProfiles copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected DownstreamBoundaryCapacityProfiles copyInto(DownstreamBoundaryCapacityProfiles copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected DownstreamBoundaryCapacityProfiles copyInto(DownstreamBoundaryCapacityProfiles copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setDownstreamBoundaryCapacityProfileSetId(downstreamBoundaryCapacityProfileSetId);
        copyObj.setLinkId(linkId);
        copyObj.setDt(dt);
        copyObj.setStartTime(startTime);
        copyObj.setCreated(created);
        copyObj.setModified(modified);
        copyObj.setCreatedBy(createdBy);
        copyObj.setModifiedBy(modifiedBy);
        copyObj.setModstamp(modstamp);

        copyObj.setId((Long)null);

        if (deepcopy)
        {


        List vDownstreamBoundaryCapacitiess = getDownstreamBoundaryCapacitiess();
        if (vDownstreamBoundaryCapacitiess != null)
        {
            for (int i = 0; i < vDownstreamBoundaryCapacitiess.size(); i++)
            {
                DownstreamBoundaryCapacities obj = (DownstreamBoundaryCapacities) vDownstreamBoundaryCapacitiess.get(i);
                copyObj.addDownstreamBoundaryCapacities(obj.copy());
            }
        }
        else
        {
            copyObj.collDownstreamBoundaryCapacitiess = null;
        }
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected DownstreamBoundaryCapacityProfiles copyInto(DownstreamBoundaryCapacityProfiles copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setDownstreamBoundaryCapacityProfileSetId(downstreamBoundaryCapacityProfileSetId);
        copyObj.setLinkId(linkId);
        copyObj.setDt(dt);
        copyObj.setStartTime(startTime);
        copyObj.setCreated(created);
        copyObj.setModified(modified);
        copyObj.setCreatedBy(createdBy);
        copyObj.setModifiedBy(modifiedBy);
        copyObj.setModstamp(modstamp);

        copyObj.setId((Long)null);

        if (deepcopy)
        {


        List vDownstreamBoundaryCapacitiess = getDownstreamBoundaryCapacitiess(con);
        if (vDownstreamBoundaryCapacitiess != null)
        {
            for (int i = 0; i < vDownstreamBoundaryCapacitiess.size(); i++)
            {
                DownstreamBoundaryCapacities obj = (DownstreamBoundaryCapacities) vDownstreamBoundaryCapacitiess.get(i);
                copyObj.addDownstreamBoundaryCapacities(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collDownstreamBoundaryCapacitiess = null;
        }
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public DownstreamBoundaryCapacityProfilesPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return DownstreamBoundaryCapacityProfilesPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("DownstreamBoundaryCapacityProfiles:\n");
        str.append("Id = ")
           .append(getId())
           .append("\n");
        str.append("DownstreamBoundaryCapacityProfileSetId = ")
           .append(getDownstreamBoundaryCapacityProfileSetId())
           .append("\n");
        str.append("LinkId = ")
           .append(getLinkId())
           .append("\n");
        str.append("Dt = ")
           .append(getDt())
           .append("\n");
        str.append("StartTime = ")
           .append(getStartTime())
           .append("\n");
        str.append("Created = ")
           .append(getCreated())
           .append("\n");
        str.append("Modified = ")
           .append(getModified())
           .append("\n");
        str.append("CreatedBy = ")
           .append(getCreatedBy())
           .append("\n");
        str.append("ModifiedBy = ")
           .append(getModifiedBy())
           .append("\n");
        str.append("Modstamp = ")
           .append(getModstamp())
           .append("\n");
        return(str.toString());
    }
}
