package com.relteq.sirius.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Nov 14 14:25:09 PST 2012]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to QueueControllers
 */
public abstract class BaseQueueControllers extends com.relteq.sirius.db.BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1352931909099L;

    /** The Peer class */
    private static final QueueControllersPeer peer =
        new QueueControllersPeer();


    /** The value for the id field */
    private Long id;

    /** The value for the type field */
    private String type;

    /** The value for the javaClass field */
    private String javaClass;

    /** The value for the created field */
    private Date created;

    /** The value for the modified field */
    private Date modified;

    /** The value for the createdBy field */
    private String createdBy;

    /** The value for the modifiedBy field */
    private String modifiedBy;

    /** The value for the modstamp field */
    private Date modstamp;


    /**
     * Get the Id
     *
     * @return Long
     */
    public Long getId()
    {
        return id;
    }


    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(Long v) throws TorqueException
    {

        if (!ObjectUtils.equals(this.id, v))
        {
            this.id = v;
            setModified(true);
        }



        // update associated Controllers
        if (collControllerss != null)
        {
            for (int i = 0; i < collControllerss.size(); i++)
            {
                ((Controllers) collControllerss.get(i))
                        .setQueueControllerId(v);
            }
        }
    }

    /**
     * Get the Type
     *
     * @return String
     */
    public String getType()
    {
        return type;
    }


    /**
     * Set the value of Type
     *
     * @param v new value
     */
    public void setType(String v) 
    {

        if (!ObjectUtils.equals(this.type, v))
        {
            this.type = v;
            setModified(true);
        }


    }

    /**
     * Get the JavaClass
     *
     * @return String
     */
    public String getJavaClass()
    {
        return javaClass;
    }


    /**
     * Set the value of JavaClass
     *
     * @param v new value
     */
    public void setJavaClass(String v) 
    {

        if (!ObjectUtils.equals(this.javaClass, v))
        {
            this.javaClass = v;
            setModified(true);
        }


    }

    /**
     * Get the Created
     *
     * @return Date
     */
    public Date getCreated()
    {
        return created;
    }


    /**
     * Set the value of Created
     *
     * @param v new value
     */
    public void setCreated(Date v) 
    {

        if (!ObjectUtils.equals(this.created, v))
        {
            this.created = v;
            setModified(true);
        }


    }

    /**
     * Get the Modified
     *
     * @return Date
     */
    public Date getModified()
    {
        return modified;
    }


    /**
     * Set the value of Modified
     *
     * @param v new value
     */
    public void setModified(Date v) 
    {

        if (!ObjectUtils.equals(this.modified, v))
        {
            this.modified = v;
            setModified(true);
        }


    }

    /**
     * Get the CreatedBy
     *
     * @return String
     */
    public String getCreatedBy()
    {
        return createdBy;
    }


    /**
     * Set the value of CreatedBy
     *
     * @param v new value
     */
    public void setCreatedBy(String v) 
    {

        if (!ObjectUtils.equals(this.createdBy, v))
        {
            this.createdBy = v;
            setModified(true);
        }


    }

    /**
     * Get the ModifiedBy
     *
     * @return String
     */
    public String getModifiedBy()
    {
        return modifiedBy;
    }


    /**
     * Set the value of ModifiedBy
     *
     * @param v new value
     */
    public void setModifiedBy(String v) 
    {

        if (!ObjectUtils.equals(this.modifiedBy, v))
        {
            this.modifiedBy = v;
            setModified(true);
        }


    }

    /**
     * Get the Modstamp
     *
     * @return Date
     */
    public Date getModstamp()
    {
        return modstamp;
    }


    /**
     * Set the value of Modstamp
     *
     * @param v new value
     */
    public void setModstamp(Date v) 
    {

        if (!ObjectUtils.equals(this.modstamp, v))
        {
            this.modstamp = v;
            setModified(true);
        }


    }

       


    /**
     * Collection to store aggregation of collControllerss
     */
    protected List collControllerss;

    /**
     * Temporary storage of collControllerss to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initControllerss()
    {
        if (collControllerss == null)
        {
            collControllerss = new ArrayList();
        }
    }


    /**
     * Method called to associate a Controllers object to this object
     * through the Controllers foreign key attribute
     *
     * @param l Controllers
     * @throws TorqueException
     */
    public void addControllers(Controllers l) throws TorqueException
    {
        getControllerss().add(l);
        l.setQueueControllers((QueueControllers) this);
    }

    /**
     * Method called to associate a Controllers object to this object
     * through the Controllers foreign key attribute using connection.
     *
     * @param l Controllers
     * @throws TorqueException
     */
    public void addControllers(Controllers l, Connection con) throws TorqueException
    {
        getControllerss(con).add(l);
        l.setQueueControllers((QueueControllers) this);
    }

    /**
     * The criteria used to select the current contents of collControllerss
     */
    private Criteria lastControllerssCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getControllerss(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List getControllerss()
        throws TorqueException
    {
        if (collControllerss == null)
        {
            collControllerss = getControllerss(new Criteria(10));
        }
        return collControllerss;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this QueueControllers has previously
     * been saved, it will retrieve related Controllerss from storage.
     * If this QueueControllers is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getControllerss(Criteria criteria) throws TorqueException
    {
        if (collControllerss == null)
        {
            if (isNew())
            {
               collControllerss = new ArrayList();
            }
            else
            {
                criteria.add(ControllersPeer.QUEUE_CONTROLLER_ID, getId() );
                collControllerss = ControllersPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(ControllersPeer.QUEUE_CONTROLLER_ID, getId());
                if (!lastControllerssCriteria.equals(criteria))
                {
                    collControllerss = ControllersPeer.doSelect(criteria);
                }
            }
        }
        lastControllerssCriteria = criteria;

        return collControllerss;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getControllerss(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getControllerss(Connection con) throws TorqueException
    {
        if (collControllerss == null)
        {
            collControllerss = getControllerss(new Criteria(10), con);
        }
        return collControllerss;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this QueueControllers has previously
     * been saved, it will retrieve related Controllerss from storage.
     * If this QueueControllers is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getControllerss(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collControllerss == null)
        {
            if (isNew())
            {
               collControllerss = new ArrayList();
            }
            else
            {
                 criteria.add(ControllersPeer.QUEUE_CONTROLLER_ID, getId());
                 collControllerss = ControllersPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(ControllersPeer.QUEUE_CONTROLLER_ID, getId());
                 if (!lastControllerssCriteria.equals(criteria))
                 {
                     collControllerss = ControllersPeer.doSelect(criteria, con);
                 }
             }
         }
         lastControllerssCriteria = criteria;

         return collControllerss;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this QueueControllers is new, it will return
     * an empty collection; or if this QueueControllers has previously
     * been saved, it will retrieve related Controllerss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in QueueControllers.
     */
    protected List getControllerssJoinControllerSets(Criteria criteria)
        throws TorqueException
    {
        if (collControllerss == null)
        {
            if (isNew())
            {
               collControllerss = new ArrayList();
            }
            else
            {
                criteria.add(ControllersPeer.QUEUE_CONTROLLER_ID, getId());
                collControllerss = ControllersPeer.doSelectJoinControllerSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ControllersPeer.QUEUE_CONTROLLER_ID, getId());
            if (!lastControllerssCriteria.equals(criteria))
            {
                collControllerss = ControllersPeer.doSelectJoinControllerSets(criteria);
            }
        }
        lastControllerssCriteria = criteria;

        return collControllerss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this QueueControllers is new, it will return
     * an empty collection; or if this QueueControllers has previously
     * been saved, it will retrieve related Controllerss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in QueueControllers.
     */
    protected List getControllerssJoinQueueControllers(Criteria criteria)
        throws TorqueException
    {
        if (collControllerss == null)
        {
            if (isNew())
            {
               collControllerss = new ArrayList();
            }
            else
            {
                criteria.add(ControllersPeer.QUEUE_CONTROLLER_ID, getId());
                collControllerss = ControllersPeer.doSelectJoinQueueControllers(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ControllersPeer.QUEUE_CONTROLLER_ID, getId());
            if (!lastControllerssCriteria.equals(criteria))
            {
                collControllerss = ControllersPeer.doSelectJoinQueueControllers(criteria);
            }
        }
        lastControllerssCriteria = criteria;

        return collControllerss;
    }



        
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
            fieldNames.add("Id");
            fieldNames.add("Type");
            fieldNames.add("JavaClass");
            fieldNames.add("Created");
            fieldNames.add("Modified");
            fieldNames.add("CreatedBy");
            fieldNames.add("ModifiedBy");
            fieldNames.add("Modstamp");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("Id"))
        {
            return getId();
        }
        if (name.equals("Type"))
        {
            return getType();
        }
        if (name.equals("JavaClass"))
        {
            return getJavaClass();
        }
        if (name.equals("Created"))
        {
            return getCreated();
        }
        if (name.equals("Modified"))
        {
            return getModified();
        }
        if (name.equals("CreatedBy"))
        {
            return getCreatedBy();
        }
        if (name.equals("ModifiedBy"))
        {
            return getModifiedBy();
        }
        if (name.equals("Modstamp"))
        {
            return getModstamp();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("Id"))
        {
            // Object fields can be null
            if (value != null && ! Long.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setId((Long) value);
            return true;
        }
        if (name.equals("Type"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setType((String) value);
            return true;
        }
        if (name.equals("JavaClass"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setJavaClass((String) value);
            return true;
        }
        if (name.equals("Created"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setCreated((Date) value);
            return true;
        }
        if (name.equals("Modified"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setModified((Date) value);
            return true;
        }
        if (name.equals("CreatedBy"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setCreatedBy((String) value);
            return true;
        }
        if (name.equals("ModifiedBy"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setModifiedBy((String) value);
            return true;
        }
        if (name.equals("Modstamp"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setModstamp((Date) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(QueueControllersPeer.ID))
        {
            return getId();
        }
        if (name.equals(QueueControllersPeer.TYPE))
        {
            return getType();
        }
        if (name.equals(QueueControllersPeer.JAVA_CLASS))
        {
            return getJavaClass();
        }
        if (name.equals(QueueControllersPeer.CREATED))
        {
            return getCreated();
        }
        if (name.equals(QueueControllersPeer.MODIFIED))
        {
            return getModified();
        }
        if (name.equals(QueueControllersPeer.CREATED_BY))
        {
            return getCreatedBy();
        }
        if (name.equals(QueueControllersPeer.MODIFIED_BY))
        {
            return getModifiedBy();
        }
        if (name.equals(QueueControllersPeer.MODSTAMP))
        {
            return getModstamp();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (QueueControllersPeer.ID.equals(name))
        {
            return setByName("Id", value);
        }
      if (QueueControllersPeer.TYPE.equals(name))
        {
            return setByName("Type", value);
        }
      if (QueueControllersPeer.JAVA_CLASS.equals(name))
        {
            return setByName("JavaClass", value);
        }
      if (QueueControllersPeer.CREATED.equals(name))
        {
            return setByName("Created", value);
        }
      if (QueueControllersPeer.MODIFIED.equals(name))
        {
            return setByName("Modified", value);
        }
      if (QueueControllersPeer.CREATED_BY.equals(name))
        {
            return setByName("CreatedBy", value);
        }
      if (QueueControllersPeer.MODIFIED_BY.equals(name))
        {
            return setByName("ModifiedBy", value);
        }
      if (QueueControllersPeer.MODSTAMP.equals(name))
        {
            return setByName("Modstamp", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return getId();
        }
        if (pos == 1)
        {
            return getType();
        }
        if (pos == 2)
        {
            return getJavaClass();
        }
        if (pos == 3)
        {
            return getCreated();
        }
        if (pos == 4)
        {
            return getModified();
        }
        if (pos == 5)
        {
            return getCreatedBy();
        }
        if (pos == 6)
        {
            return getModifiedBy();
        }
        if (pos == 7)
        {
            return getModstamp();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("Id", value);
        }
    if (position == 1)
        {
            return setByName("Type", value);
        }
    if (position == 2)
        {
            return setByName("JavaClass", value);
        }
    if (position == 3)
        {
            return setByName("Created", value);
        }
    if (position == 4)
        {
            return setByName("Modified", value);
        }
    if (position == 5)
        {
            return setByName("CreatedBy", value);
        }
    if (position == 6)
        {
            return setByName("ModifiedBy", value);
        }
    if (position == 7)
        {
            return setByName("Modstamp", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(QueueControllersPeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    QueueControllersPeer.doInsert((QueueControllers) this, con);
                    setNew(false);
                }
                else
                {
                    QueueControllersPeer.doUpdate((QueueControllers) this, con);
                }
            }


            if (collControllerss != null)
            {
                for (int i = 0; i < collControllerss.size(); i++)
                {
                    ((Controllers) collControllerss.get(i)).save(con);
                }
            }
            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
        setId(new Long(((NumberKey) key).longValue()));
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
        setId(new Long(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getId());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public QueueControllers copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public QueueControllers copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public QueueControllers copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new QueueControllers(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public QueueControllers copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new QueueControllers(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected QueueControllers copyInto(QueueControllers copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected QueueControllers copyInto(QueueControllers copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected QueueControllers copyInto(QueueControllers copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setType(type);
        copyObj.setJavaClass(javaClass);
        copyObj.setCreated(created);
        copyObj.setModified(modified);
        copyObj.setCreatedBy(createdBy);
        copyObj.setModifiedBy(modifiedBy);
        copyObj.setModstamp(modstamp);

        copyObj.setId((Long)null);

        if (deepcopy)
        {


        List vControllerss = getControllerss();
        if (vControllerss != null)
        {
            for (int i = 0; i < vControllerss.size(); i++)
            {
                Controllers obj = (Controllers) vControllerss.get(i);
                copyObj.addControllers(obj.copy());
            }
        }
        else
        {
            copyObj.collControllerss = null;
        }
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected QueueControllers copyInto(QueueControllers copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setType(type);
        copyObj.setJavaClass(javaClass);
        copyObj.setCreated(created);
        copyObj.setModified(modified);
        copyObj.setCreatedBy(createdBy);
        copyObj.setModifiedBy(modifiedBy);
        copyObj.setModstamp(modstamp);

        copyObj.setId((Long)null);

        if (deepcopy)
        {


        List vControllerss = getControllerss(con);
        if (vControllerss != null)
        {
            for (int i = 0; i < vControllerss.size(); i++)
            {
                Controllers obj = (Controllers) vControllerss.get(i);
                copyObj.addControllers(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collControllerss = null;
        }
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public QueueControllersPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return QueueControllersPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("QueueControllers:\n");
        str.append("Id = ")
           .append(getId())
           .append("\n");
        str.append("Type = ")
           .append(getType())
           .append("\n");
        str.append("JavaClass = ")
           .append(getJavaClass())
           .append("\n");
        str.append("Created = ")
           .append(getCreated())
           .append("\n");
        str.append("Modified = ")
           .append(getModified())
           .append("\n");
        str.append("CreatedBy = ")
           .append(getCreatedBy())
           .append("\n");
        str.append("ModifiedBy = ")
           .append(getModifiedBy())
           .append("\n");
        str.append("Modstamp = ")
           .append(getModstamp())
           .append("\n");
        return(str.toString());
    }
}
