package com.relteq.sirius.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Nov 14 14:25:09 PST 2012]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to WeavingFactorSets
 */
public abstract class BaseWeavingFactorSets extends com.relteq.sirius.db.BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1352931909099L;

    /** The Peer class */
    private static final WeavingFactorSetsPeer peer =
        new WeavingFactorSetsPeer();


    /** The value for the id field */
    private Long id;

    /** The value for the projectId field */
    private Long projectId;

    /** The value for the name field */
    private String name;

    /** The value for the description field */
    private String description;

    /** The value for the created field */
    private Date created;

    /** The value for the modified field */
    private Date modified;

    /** The value for the createdBy field */
    private String createdBy;

    /** The value for the modifiedBy field */
    private String modifiedBy;

    /** The value for the modstamp field */
    private Date modstamp;


    /**
     * Get the Id
     *
     * @return Long
     */
    public Long getId()
    {
        return id;
    }


    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(Long v) throws TorqueException
    {

        if (!ObjectUtils.equals(this.id, v))
        {
            this.id = v;
            setModified(true);
        }



        // update associated WeavingFactors
        if (collWeavingFactorss != null)
        {
            for (int i = 0; i < collWeavingFactorss.size(); i++)
            {
                ((WeavingFactors) collWeavingFactorss.get(i))
                        .setWeavingFactorSetId(v);
            }
        }

        // update associated Scenarios
        if (collScenarioss != null)
        {
            for (int i = 0; i < collScenarioss.size(); i++)
            {
                ((Scenarios) collScenarioss.get(i))
                        .setWeavingFactorSetId(v);
            }
        }
    }

    /**
     * Get the ProjectId
     *
     * @return Long
     */
    public Long getProjectId()
    {
        return projectId;
    }


    /**
     * Set the value of ProjectId
     *
     * @param v new value
     */
    public void setProjectId(Long v) throws TorqueException
    {

        if (!ObjectUtils.equals(this.projectId, v))
        {
            this.projectId = v;
            setModified(true);
        }


        if (aProjects != null && !ObjectUtils.equals(aProjects.getId(), v))
        {
            aProjects = null;
        }

    }

    /**
     * Get the Name
     *
     * @return String
     */
    public String getName()
    {
        return name;
    }


    /**
     * Set the value of Name
     *
     * @param v new value
     */
    public void setName(String v) 
    {

        if (!ObjectUtils.equals(this.name, v))
        {
            this.name = v;
            setModified(true);
        }


    }

    /**
     * Get the Description
     *
     * @return String
     */
    public String getDescription()
    {
        return description;
    }


    /**
     * Set the value of Description
     *
     * @param v new value
     */
    public void setDescription(String v) 
    {

        if (!ObjectUtils.equals(this.description, v))
        {
            this.description = v;
            setModified(true);
        }


    }

    /**
     * Get the Created
     *
     * @return Date
     */
    public Date getCreated()
    {
        return created;
    }


    /**
     * Set the value of Created
     *
     * @param v new value
     */
    public void setCreated(Date v) 
    {

        if (!ObjectUtils.equals(this.created, v))
        {
            this.created = v;
            setModified(true);
        }


    }

    /**
     * Get the Modified
     *
     * @return Date
     */
    public Date getModified()
    {
        return modified;
    }


    /**
     * Set the value of Modified
     *
     * @param v new value
     */
    public void setModified(Date v) 
    {

        if (!ObjectUtils.equals(this.modified, v))
        {
            this.modified = v;
            setModified(true);
        }


    }

    /**
     * Get the CreatedBy
     *
     * @return String
     */
    public String getCreatedBy()
    {
        return createdBy;
    }


    /**
     * Set the value of CreatedBy
     *
     * @param v new value
     */
    public void setCreatedBy(String v) 
    {

        if (!ObjectUtils.equals(this.createdBy, v))
        {
            this.createdBy = v;
            setModified(true);
        }


    }

    /**
     * Get the ModifiedBy
     *
     * @return String
     */
    public String getModifiedBy()
    {
        return modifiedBy;
    }


    /**
     * Set the value of ModifiedBy
     *
     * @param v new value
     */
    public void setModifiedBy(String v) 
    {

        if (!ObjectUtils.equals(this.modifiedBy, v))
        {
            this.modifiedBy = v;
            setModified(true);
        }


    }

    /**
     * Get the Modstamp
     *
     * @return Date
     */
    public Date getModstamp()
    {
        return modstamp;
    }


    /**
     * Set the value of Modstamp
     *
     * @param v new value
     */
    public void setModstamp(Date v) 
    {

        if (!ObjectUtils.equals(this.modstamp, v))
        {
            this.modstamp = v;
            setModified(true);
        }


    }

    



    private Projects aProjects;

    /**
     * Declares an association between this object and a Projects object
     *
     * @param v Projects
     * @throws TorqueException
     */
    public void setProjects(Projects v) throws TorqueException
    {
        if (v == null)
        {
            setProjectId((Long) null);
        }
        else
        {
            setProjectId(v.getId());
        }
        aProjects = v;
    }


    /**
     * Returns the associated Projects object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated Projects object
     * @throws TorqueException
     */
    public Projects getProjects()
        throws TorqueException
    {
        if (aProjects == null && (!ObjectUtils.equals(this.projectId, null)))
        {
            aProjects = ProjectsPeer.retrieveByPK(SimpleKey.keyFor(this.projectId));
        }
        return aProjects;
    }

    /**
     * Return the associated Projects object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated Projects object
     * @throws TorqueException
     */
    public Projects getProjects(Connection connection)
        throws TorqueException
    {
        if (aProjects == null && (!ObjectUtils.equals(this.projectId, null)))
        {
            aProjects = ProjectsPeer.retrieveByPK(SimpleKey.keyFor(this.projectId), connection);
        }
        return aProjects;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setProjectsKey(ObjectKey key) throws TorqueException
    {

        setProjectId(new Long(((NumberKey) key).longValue()));
    }
   


    /**
     * Collection to store aggregation of collWeavingFactorss
     */
    protected List collWeavingFactorss;

    /**
     * Temporary storage of collWeavingFactorss to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initWeavingFactorss()
    {
        if (collWeavingFactorss == null)
        {
            collWeavingFactorss = new ArrayList();
        }
    }


    /**
     * Method called to associate a WeavingFactors object to this object
     * through the WeavingFactors foreign key attribute
     *
     * @param l WeavingFactors
     * @throws TorqueException
     */
    public void addWeavingFactors(WeavingFactors l) throws TorqueException
    {
        getWeavingFactorss().add(l);
        l.setWeavingFactorSets((WeavingFactorSets) this);
    }

    /**
     * Method called to associate a WeavingFactors object to this object
     * through the WeavingFactors foreign key attribute using connection.
     *
     * @param l WeavingFactors
     * @throws TorqueException
     */
    public void addWeavingFactors(WeavingFactors l, Connection con) throws TorqueException
    {
        getWeavingFactorss(con).add(l);
        l.setWeavingFactorSets((WeavingFactorSets) this);
    }

    /**
     * The criteria used to select the current contents of collWeavingFactorss
     */
    private Criteria lastWeavingFactorssCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getWeavingFactorss(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List getWeavingFactorss()
        throws TorqueException
    {
        if (collWeavingFactorss == null)
        {
            collWeavingFactorss = getWeavingFactorss(new Criteria(10));
        }
        return collWeavingFactorss;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets has previously
     * been saved, it will retrieve related WeavingFactorss from storage.
     * If this WeavingFactorSets is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getWeavingFactorss(Criteria criteria) throws TorqueException
    {
        if (collWeavingFactorss == null)
        {
            if (isNew())
            {
               collWeavingFactorss = new ArrayList();
            }
            else
            {
                criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId() );
                collWeavingFactorss = WeavingFactorsPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId());
                if (!lastWeavingFactorssCriteria.equals(criteria))
                {
                    collWeavingFactorss = WeavingFactorsPeer.doSelect(criteria);
                }
            }
        }
        lastWeavingFactorssCriteria = criteria;

        return collWeavingFactorss;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getWeavingFactorss(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getWeavingFactorss(Connection con) throws TorqueException
    {
        if (collWeavingFactorss == null)
        {
            collWeavingFactorss = getWeavingFactorss(new Criteria(10), con);
        }
        return collWeavingFactorss;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets has previously
     * been saved, it will retrieve related WeavingFactorss from storage.
     * If this WeavingFactorSets is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getWeavingFactorss(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collWeavingFactorss == null)
        {
            if (isNew())
            {
               collWeavingFactorss = new ArrayList();
            }
            else
            {
                 criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId());
                 collWeavingFactorss = WeavingFactorsPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId());
                 if (!lastWeavingFactorssCriteria.equals(criteria))
                 {
                     collWeavingFactorss = WeavingFactorsPeer.doSelect(criteria, con);
                 }
             }
         }
         lastWeavingFactorssCriteria = criteria;

         return collWeavingFactorss;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related WeavingFactorss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getWeavingFactorssJoinWeavingFactorSets(Criteria criteria)
        throws TorqueException
    {
        if (collWeavingFactorss == null)
        {
            if (isNew())
            {
               collWeavingFactorss = new ArrayList();
            }
            else
            {
                criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId());
                collWeavingFactorss = WeavingFactorsPeer.doSelectJoinWeavingFactorSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastWeavingFactorssCriteria.equals(criteria))
            {
                collWeavingFactorss = WeavingFactorsPeer.doSelectJoinWeavingFactorSets(criteria);
            }
        }
        lastWeavingFactorssCriteria = criteria;

        return collWeavingFactorss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related WeavingFactorss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getWeavingFactorssJoinLinkFamiliesRelatedByInLinkId(Criteria criteria)
        throws TorqueException
    {
        if (collWeavingFactorss == null)
        {
            if (isNew())
            {
               collWeavingFactorss = new ArrayList();
            }
            else
            {
                criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId());
                collWeavingFactorss = WeavingFactorsPeer.doSelectJoinLinkFamiliesRelatedByInLinkId(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastWeavingFactorssCriteria.equals(criteria))
            {
                collWeavingFactorss = WeavingFactorsPeer.doSelectJoinLinkFamiliesRelatedByInLinkId(criteria);
            }
        }
        lastWeavingFactorssCriteria = criteria;

        return collWeavingFactorss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related WeavingFactorss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getWeavingFactorssJoinLinkFamiliesRelatedByOutLinkId(Criteria criteria)
        throws TorqueException
    {
        if (collWeavingFactorss == null)
        {
            if (isNew())
            {
               collWeavingFactorss = new ArrayList();
            }
            else
            {
                criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId());
                collWeavingFactorss = WeavingFactorsPeer.doSelectJoinLinkFamiliesRelatedByOutLinkId(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastWeavingFactorssCriteria.equals(criteria))
            {
                collWeavingFactorss = WeavingFactorsPeer.doSelectJoinLinkFamiliesRelatedByOutLinkId(criteria);
            }
        }
        lastWeavingFactorssCriteria = criteria;

        return collWeavingFactorss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related WeavingFactorss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getWeavingFactorssJoinVehicleTypes(Criteria criteria)
        throws TorqueException
    {
        if (collWeavingFactorss == null)
        {
            if (isNew())
            {
               collWeavingFactorss = new ArrayList();
            }
            else
            {
                criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId());
                collWeavingFactorss = WeavingFactorsPeer.doSelectJoinVehicleTypes(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(WeavingFactorsPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastWeavingFactorssCriteria.equals(criteria))
            {
                collWeavingFactorss = WeavingFactorsPeer.doSelectJoinVehicleTypes(criteria);
            }
        }
        lastWeavingFactorssCriteria = criteria;

        return collWeavingFactorss;
    }





    /**
     * Collection to store aggregation of collScenarioss
     */
    protected List collScenarioss;

    /**
     * Temporary storage of collScenarioss to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initScenarioss()
    {
        if (collScenarioss == null)
        {
            collScenarioss = new ArrayList();
        }
    }


    /**
     * Method called to associate a Scenarios object to this object
     * through the Scenarios foreign key attribute
     *
     * @param l Scenarios
     * @throws TorqueException
     */
    public void addScenarios(Scenarios l) throws TorqueException
    {
        getScenarioss().add(l);
        l.setWeavingFactorSets((WeavingFactorSets) this);
    }

    /**
     * Method called to associate a Scenarios object to this object
     * through the Scenarios foreign key attribute using connection.
     *
     * @param l Scenarios
     * @throws TorqueException
     */
    public void addScenarios(Scenarios l, Connection con) throws TorqueException
    {
        getScenarioss(con).add(l);
        l.setWeavingFactorSets((WeavingFactorSets) this);
    }

    /**
     * The criteria used to select the current contents of collScenarioss
     */
    private Criteria lastScenariossCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getScenarioss(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List getScenarioss()
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            collScenarioss = getScenarioss(new Criteria(10));
        }
        return collScenarioss;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     * If this WeavingFactorSets is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getScenarioss(Criteria criteria) throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId() );
                collScenarioss = ScenariosPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                if (!lastScenariossCriteria.equals(criteria))
                {
                    collScenarioss = ScenariosPeer.doSelect(criteria);
                }
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getScenarioss(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getScenarioss(Connection con) throws TorqueException
    {
        if (collScenarioss == null)
        {
            collScenarioss = getScenarioss(new Criteria(10), con);
        }
        return collScenarioss;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     * If this WeavingFactorSets is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getScenarioss(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                 criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                 collScenarioss = ScenariosPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                 if (!lastScenariossCriteria.equals(criteria))
                 {
                     collScenarioss = ScenariosPeer.doSelect(criteria, con);
                 }
             }
         }
         lastScenariossCriteria = criteria;

         return collScenarioss;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinProjects(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinProjects(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinProjects(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinNetworkConnectionSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinNetworkConnectionSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinNetworkConnectionSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinSignalSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinSignalSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinSignalSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinSensorSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinSensorSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinSensorSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinInitialDensitySets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinInitialDensitySets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinInitialDensitySets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinFundamentalDiagramProfileSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinFundamentalDiagramProfileSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinFundamentalDiagramProfileSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinDemandProfileSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinDemandProfileSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinDemandProfileSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinDownstreamBoundaryCapacityProfileSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinDownstreamBoundaryCapacityProfileSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinDownstreamBoundaryCapacityProfileSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinSplitRatioProfileSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinSplitRatioProfileSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinSplitRatioProfileSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinWeavingFactorSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinWeavingFactorSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinWeavingFactorSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinControllerSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinControllerSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinControllerSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinEventSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinEventSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinEventSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinEnkfNoiseParameterSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinEnkfNoiseParameterSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinEnkfNoiseParameterSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this WeavingFactorSets is new, it will return
     * an empty collection; or if this WeavingFactorSets has previously
     * been saved, it will retrieve related Scenarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WeavingFactorSets.
     */
    protected List getScenariossJoinVehicleTypeSets(Criteria criteria)
        throws TorqueException
    {
        if (collScenarioss == null)
        {
            if (isNew())
            {
               collScenarioss = new ArrayList();
            }
            else
            {
                criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
                collScenarioss = ScenariosPeer.doSelectJoinVehicleTypeSets(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(ScenariosPeer.WEAVING_FACTOR_SET_ID, getId());
            if (!lastScenariossCriteria.equals(criteria))
            {
                collScenarioss = ScenariosPeer.doSelectJoinVehicleTypeSets(criteria);
            }
        }
        lastScenariossCriteria = criteria;

        return collScenarioss;
    }



        
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
            fieldNames.add("Id");
            fieldNames.add("ProjectId");
            fieldNames.add("Name");
            fieldNames.add("Description");
            fieldNames.add("Created");
            fieldNames.add("Modified");
            fieldNames.add("CreatedBy");
            fieldNames.add("ModifiedBy");
            fieldNames.add("Modstamp");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("Id"))
        {
            return getId();
        }
        if (name.equals("ProjectId"))
        {
            return getProjectId();
        }
        if (name.equals("Name"))
        {
            return getName();
        }
        if (name.equals("Description"))
        {
            return getDescription();
        }
        if (name.equals("Created"))
        {
            return getCreated();
        }
        if (name.equals("Modified"))
        {
            return getModified();
        }
        if (name.equals("CreatedBy"))
        {
            return getCreatedBy();
        }
        if (name.equals("ModifiedBy"))
        {
            return getModifiedBy();
        }
        if (name.equals("Modstamp"))
        {
            return getModstamp();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("Id"))
        {
            // Object fields can be null
            if (value != null && ! Long.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setId((Long) value);
            return true;
        }
        if (name.equals("ProjectId"))
        {
            // Object fields can be null
            if (value != null && ! Long.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setProjectId((Long) value);
            return true;
        }
        if (name.equals("Name"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setName((String) value);
            return true;
        }
        if (name.equals("Description"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setDescription((String) value);
            return true;
        }
        if (name.equals("Created"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setCreated((Date) value);
            return true;
        }
        if (name.equals("Modified"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setModified((Date) value);
            return true;
        }
        if (name.equals("CreatedBy"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setCreatedBy((String) value);
            return true;
        }
        if (name.equals("ModifiedBy"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setModifiedBy((String) value);
            return true;
        }
        if (name.equals("Modstamp"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setModstamp((Date) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(WeavingFactorSetsPeer.ID))
        {
            return getId();
        }
        if (name.equals(WeavingFactorSetsPeer.PROJECT_ID))
        {
            return getProjectId();
        }
        if (name.equals(WeavingFactorSetsPeer.NAME))
        {
            return getName();
        }
        if (name.equals(WeavingFactorSetsPeer.DESCRIPTION))
        {
            return getDescription();
        }
        if (name.equals(WeavingFactorSetsPeer.CREATED))
        {
            return getCreated();
        }
        if (name.equals(WeavingFactorSetsPeer.MODIFIED))
        {
            return getModified();
        }
        if (name.equals(WeavingFactorSetsPeer.CREATED_BY))
        {
            return getCreatedBy();
        }
        if (name.equals(WeavingFactorSetsPeer.MODIFIED_BY))
        {
            return getModifiedBy();
        }
        if (name.equals(WeavingFactorSetsPeer.MODSTAMP))
        {
            return getModstamp();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (WeavingFactorSetsPeer.ID.equals(name))
        {
            return setByName("Id", value);
        }
      if (WeavingFactorSetsPeer.PROJECT_ID.equals(name))
        {
            return setByName("ProjectId", value);
        }
      if (WeavingFactorSetsPeer.NAME.equals(name))
        {
            return setByName("Name", value);
        }
      if (WeavingFactorSetsPeer.DESCRIPTION.equals(name))
        {
            return setByName("Description", value);
        }
      if (WeavingFactorSetsPeer.CREATED.equals(name))
        {
            return setByName("Created", value);
        }
      if (WeavingFactorSetsPeer.MODIFIED.equals(name))
        {
            return setByName("Modified", value);
        }
      if (WeavingFactorSetsPeer.CREATED_BY.equals(name))
        {
            return setByName("CreatedBy", value);
        }
      if (WeavingFactorSetsPeer.MODIFIED_BY.equals(name))
        {
            return setByName("ModifiedBy", value);
        }
      if (WeavingFactorSetsPeer.MODSTAMP.equals(name))
        {
            return setByName("Modstamp", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return getId();
        }
        if (pos == 1)
        {
            return getProjectId();
        }
        if (pos == 2)
        {
            return getName();
        }
        if (pos == 3)
        {
            return getDescription();
        }
        if (pos == 4)
        {
            return getCreated();
        }
        if (pos == 5)
        {
            return getModified();
        }
        if (pos == 6)
        {
            return getCreatedBy();
        }
        if (pos == 7)
        {
            return getModifiedBy();
        }
        if (pos == 8)
        {
            return getModstamp();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("Id", value);
        }
    if (position == 1)
        {
            return setByName("ProjectId", value);
        }
    if (position == 2)
        {
            return setByName("Name", value);
        }
    if (position == 3)
        {
            return setByName("Description", value);
        }
    if (position == 4)
        {
            return setByName("Created", value);
        }
    if (position == 5)
        {
            return setByName("Modified", value);
        }
    if (position == 6)
        {
            return setByName("CreatedBy", value);
        }
    if (position == 7)
        {
            return setByName("ModifiedBy", value);
        }
    if (position == 8)
        {
            return setByName("Modstamp", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(WeavingFactorSetsPeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    WeavingFactorSetsPeer.doInsert((WeavingFactorSets) this, con);
                    setNew(false);
                }
                else
                {
                    WeavingFactorSetsPeer.doUpdate((WeavingFactorSets) this, con);
                }
            }


            if (collWeavingFactorss != null)
            {
                for (int i = 0; i < collWeavingFactorss.size(); i++)
                {
                    ((WeavingFactors) collWeavingFactorss.get(i)).save(con);
                }
            }

            if (collScenarioss != null)
            {
                for (int i = 0; i < collScenarioss.size(); i++)
                {
                    ((Scenarios) collScenarioss.get(i)).save(con);
                }
            }
            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
        setId(new Long(((NumberKey) key).longValue()));
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
        setId(new Long(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getId());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public WeavingFactorSets copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public WeavingFactorSets copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public WeavingFactorSets copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new WeavingFactorSets(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public WeavingFactorSets copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new WeavingFactorSets(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected WeavingFactorSets copyInto(WeavingFactorSets copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected WeavingFactorSets copyInto(WeavingFactorSets copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected WeavingFactorSets copyInto(WeavingFactorSets copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setProjectId(projectId);
        copyObj.setName(name);
        copyObj.setDescription(description);
        copyObj.setCreated(created);
        copyObj.setModified(modified);
        copyObj.setCreatedBy(createdBy);
        copyObj.setModifiedBy(modifiedBy);
        copyObj.setModstamp(modstamp);

        copyObj.setId((Long)null);

        if (deepcopy)
        {


        List vWeavingFactorss = getWeavingFactorss();
        if (vWeavingFactorss != null)
        {
            for (int i = 0; i < vWeavingFactorss.size(); i++)
            {
                WeavingFactors obj = (WeavingFactors) vWeavingFactorss.get(i);
                copyObj.addWeavingFactors(obj.copy());
            }
        }
        else
        {
            copyObj.collWeavingFactorss = null;
        }


        List vScenarioss = getScenarioss();
        if (vScenarioss != null)
        {
            for (int i = 0; i < vScenarioss.size(); i++)
            {
                Scenarios obj = (Scenarios) vScenarioss.get(i);
                copyObj.addScenarios(obj.copy());
            }
        }
        else
        {
            copyObj.collScenarioss = null;
        }
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected WeavingFactorSets copyInto(WeavingFactorSets copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setProjectId(projectId);
        copyObj.setName(name);
        copyObj.setDescription(description);
        copyObj.setCreated(created);
        copyObj.setModified(modified);
        copyObj.setCreatedBy(createdBy);
        copyObj.setModifiedBy(modifiedBy);
        copyObj.setModstamp(modstamp);

        copyObj.setId((Long)null);

        if (deepcopy)
        {


        List vWeavingFactorss = getWeavingFactorss(con);
        if (vWeavingFactorss != null)
        {
            for (int i = 0; i < vWeavingFactorss.size(); i++)
            {
                WeavingFactors obj = (WeavingFactors) vWeavingFactorss.get(i);
                copyObj.addWeavingFactors(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collWeavingFactorss = null;
        }


        List vScenarioss = getScenarioss(con);
        if (vScenarioss != null)
        {
            for (int i = 0; i < vScenarioss.size(); i++)
            {
                Scenarios obj = (Scenarios) vScenarioss.get(i);
                copyObj.addScenarios(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collScenarioss = null;
        }
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public WeavingFactorSetsPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return WeavingFactorSetsPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("WeavingFactorSets:\n");
        str.append("Id = ")
           .append(getId())
           .append("\n");
        str.append("ProjectId = ")
           .append(getProjectId())
           .append("\n");
        str.append("Name = ")
           .append(getName())
           .append("\n");
        str.append("Description = ")
           .append(getDescription())
           .append("\n");
        str.append("Created = ")
           .append(getCreated())
           .append("\n");
        str.append("Modified = ")
           .append(getModified())
           .append("\n");
        str.append("CreatedBy = ")
           .append(getCreatedBy())
           .append("\n");
        str.append("ModifiedBy = ")
           .append(getModifiedBy())
           .append("\n");
        str.append("Modstamp = ")
           .append(getModstamp())
           .append("\n");
        return(str.toString());
    }
}
