//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.14 at 02:24:14 PM PST 
//


package com.relteq.sirius.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}description" minOccurs="0"/>
 *         &lt;element ref="{}settings" minOccurs="0"/>
 *         &lt;element ref="{}NetworkList" minOccurs="0"/>
 *         &lt;element ref="{}SignalList" minOccurs="0"/>
 *         &lt;element ref="{}SensorList" minOccurs="0"/>
 *         &lt;element ref="{}InitialDensitySet" minOccurs="0"/>
 *         &lt;element ref="{}WeavingFactorSet" minOccurs="0"/>
 *         &lt;element ref="{}SplitRatioProfileSet" minOccurs="0"/>
 *         &lt;element ref="{}DownstreamBoundaryCapacityProfileSet" minOccurs="0"/>
 *         &lt;element ref="{}EventSet" minOccurs="0"/>
 *         &lt;element ref="{}DemandProfileSet" minOccurs="0"/>
 *         &lt;element ref="{}ControllerSet" minOccurs="0"/>
 *         &lt;element ref="{}FundamentalDiagramProfileSet" minOccurs="0"/>
 *         &lt;element ref="{}NetworkConnections" minOccurs="0"/>
 *         &lt;element ref="{}DestinationNetworks" minOccurs="0"/>
 *         &lt;element ref="{}Routes" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "scenario")
public class Scenario {

    protected String description;
    protected Settings settings;
    @XmlElement(name = "NetworkList")
    protected NetworkList networkList;
    @XmlElement(name = "SignalList")
    protected SignalList signalList;
    @XmlElement(name = "SensorList")
    protected SensorList sensorList;
    @XmlElement(name = "InitialDensitySet")
    protected InitialDensitySet initialDensitySet;
    @XmlElement(name = "WeavingFactorSet")
    protected WeavingFactorSet weavingFactorSet;
    @XmlElement(name = "SplitRatioProfileSet")
    protected SplitRatioProfileSet splitRatioProfileSet;
    @XmlElement(name = "DownstreamBoundaryCapacityProfileSet")
    protected DownstreamBoundaryCapacityProfileSet downstreamBoundaryCapacityProfileSet;
    @XmlElement(name = "EventSet")
    protected EventSet eventSet;
    @XmlElement(name = "DemandProfileSet")
    protected DemandProfileSet demandProfileSet;
    @XmlElement(name = "ControllerSet")
    protected ControllerSet controllerSet;
    @XmlElement(name = "FundamentalDiagramProfileSet")
    protected FundamentalDiagramProfileSet fundamentalDiagramProfileSet;
    @XmlElement(name = "NetworkConnections")
    protected NetworkConnections networkConnections;
    @XmlElement(name = "DestinationNetworks")
    protected DestinationNetworks destinationNetworks;
    @XmlElement(name = "Routes")
    protected Routes routes;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "schemaVersion", required = true)
    protected String schemaVersion;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Settings }
     *     
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings }
     *     
     */
    public void setSettings(Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the networkList property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkList }
     *     
     */
    public NetworkList getNetworkList() {
        return networkList;
    }

    /**
     * Sets the value of the networkList property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkList }
     *     
     */
    public void setNetworkList(NetworkList value) {
        this.networkList = value;
    }

    /**
     * Gets the value of the signalList property.
     * 
     * @return
     *     possible object is
     *     {@link SignalList }
     *     
     */
    public SignalList getSignalList() {
        return signalList;
    }

    /**
     * Sets the value of the signalList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalList }
     *     
     */
    public void setSignalList(SignalList value) {
        this.signalList = value;
    }

    /**
     * Gets the value of the sensorList property.
     * 
     * @return
     *     possible object is
     *     {@link SensorList }
     *     
     */
    public SensorList getSensorList() {
        return sensorList;
    }

    /**
     * Sets the value of the sensorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SensorList }
     *     
     */
    public void setSensorList(SensorList value) {
        this.sensorList = value;
    }

    /**
     * Gets the value of the initialDensitySet property.
     * 
     * @return
     *     possible object is
     *     {@link InitialDensitySet }
     *     
     */
    public InitialDensitySet getInitialDensitySet() {
        return initialDensitySet;
    }

    /**
     * Sets the value of the initialDensitySet property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialDensitySet }
     *     
     */
    public void setInitialDensitySet(InitialDensitySet value) {
        this.initialDensitySet = value;
    }

    /**
     * Gets the value of the weavingFactorSet property.
     * 
     * @return
     *     possible object is
     *     {@link WeavingFactorSet }
     *     
     */
    public WeavingFactorSet getWeavingFactorSet() {
        return weavingFactorSet;
    }

    /**
     * Sets the value of the weavingFactorSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeavingFactorSet }
     *     
     */
    public void setWeavingFactorSet(WeavingFactorSet value) {
        this.weavingFactorSet = value;
    }

    /**
     * Gets the value of the splitRatioProfileSet property.
     * 
     * @return
     *     possible object is
     *     {@link SplitRatioProfileSet }
     *     
     */
    public SplitRatioProfileSet getSplitRatioProfileSet() {
        return splitRatioProfileSet;
    }

    /**
     * Sets the value of the splitRatioProfileSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplitRatioProfileSet }
     *     
     */
    public void setSplitRatioProfileSet(SplitRatioProfileSet value) {
        this.splitRatioProfileSet = value;
    }

    /**
     * Gets the value of the downstreamBoundaryCapacityProfileSet property.
     * 
     * @return
     *     possible object is
     *     {@link DownstreamBoundaryCapacityProfileSet }
     *     
     */
    public DownstreamBoundaryCapacityProfileSet getDownstreamBoundaryCapacityProfileSet() {
        return downstreamBoundaryCapacityProfileSet;
    }

    /**
     * Sets the value of the downstreamBoundaryCapacityProfileSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DownstreamBoundaryCapacityProfileSet }
     *     
     */
    public void setDownstreamBoundaryCapacityProfileSet(DownstreamBoundaryCapacityProfileSet value) {
        this.downstreamBoundaryCapacityProfileSet = value;
    }

    /**
     * Gets the value of the eventSet property.
     * 
     * @return
     *     possible object is
     *     {@link EventSet }
     *     
     */
    public EventSet getEventSet() {
        return eventSet;
    }

    /**
     * Sets the value of the eventSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventSet }
     *     
     */
    public void setEventSet(EventSet value) {
        this.eventSet = value;
    }

    /**
     * Gets the value of the demandProfileSet property.
     * 
     * @return
     *     possible object is
     *     {@link DemandProfileSet }
     *     
     */
    public DemandProfileSet getDemandProfileSet() {
        return demandProfileSet;
    }

    /**
     * Sets the value of the demandProfileSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemandProfileSet }
     *     
     */
    public void setDemandProfileSet(DemandProfileSet value) {
        this.demandProfileSet = value;
    }

    /**
     * Gets the value of the controllerSet property.
     * 
     * @return
     *     possible object is
     *     {@link ControllerSet }
     *     
     */
    public ControllerSet getControllerSet() {
        return controllerSet;
    }

    /**
     * Sets the value of the controllerSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControllerSet }
     *     
     */
    public void setControllerSet(ControllerSet value) {
        this.controllerSet = value;
    }

    /**
     * Gets the value of the fundamentalDiagramProfileSet property.
     * 
     * @return
     *     possible object is
     *     {@link FundamentalDiagramProfileSet }
     *     
     */
    public FundamentalDiagramProfileSet getFundamentalDiagramProfileSet() {
        return fundamentalDiagramProfileSet;
    }

    /**
     * Sets the value of the fundamentalDiagramProfileSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundamentalDiagramProfileSet }
     *     
     */
    public void setFundamentalDiagramProfileSet(FundamentalDiagramProfileSet value) {
        this.fundamentalDiagramProfileSet = value;
    }

    /**
     * Gets the value of the networkConnections property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkConnections }
     *     
     */
    public NetworkConnections getNetworkConnections() {
        return networkConnections;
    }

    /**
     * Sets the value of the networkConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkConnections }
     *     
     */
    public void setNetworkConnections(NetworkConnections value) {
        this.networkConnections = value;
    }

    /**
     * Gets the value of the destinationNetworks property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationNetworks }
     *     
     */
    public DestinationNetworks getDestinationNetworks() {
        return destinationNetworks;
    }

    /**
     * Sets the value of the destinationNetworks property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationNetworks }
     *     
     */
    public void setDestinationNetworks(DestinationNetworks value) {
        this.destinationNetworks = value;
    }

    /**
     * Gets the value of the routes property.
     * 
     * @return
     *     possible object is
     *     {@link Routes }
     *     
     */
    public Routes getRoutes() {
        return routes;
    }

    /**
     * Sets the value of the routes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Routes }
     *     
     */
    public void setRoutes(Routes value) {
        this.routes = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

}
