//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.14 at 02:24:14 PM PST 
//


package com.relteq.sirius.jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}display_position" minOccurs="0"/>
 *         &lt;element ref="{}link_reference" minOccurs="0"/>
 *         &lt;element ref="{}parameters" minOccurs="0"/>
 *         &lt;element ref="{}table" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="link_position" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="static_point|static_area|moving_point"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="sensor_id_original" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lane_number" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="health_status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "sensor")
public class Sensor {

    @XmlElement(name = "display_position")
    protected DisplayPosition displayPosition;
    @XmlElement(name = "link_reference")
    protected LinkReference linkReference;
    protected Parameters parameters;
    protected Table table;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "link_position")
    protected BigDecimal linkPosition;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "sensor_id_original")
    protected String sensorIdOriginal;
    @XmlAttribute(name = "lane_number")
    protected BigInteger laneNumber;
    @XmlAttribute(name = "health_status")
    protected BigDecimal healthStatus;

    /**
     * Gets the value of the displayPosition property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayPosition }
     *     
     */
    public DisplayPosition getDisplayPosition() {
        return displayPosition;
    }

    /**
     * Sets the value of the displayPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayPosition }
     *     
     */
    public void setDisplayPosition(DisplayPosition value) {
        this.displayPosition = value;
    }

    /**
     * Gets the value of the linkReference property.
     * 
     * @return
     *     possible object is
     *     {@link LinkReference }
     *     
     */
    public LinkReference getLinkReference() {
        return linkReference;
    }

    /**
     * Sets the value of the linkReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkReference }
     *     
     */
    public void setLinkReference(LinkReference value) {
        this.linkReference = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link Table }
     *     
     */
    public Table getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link Table }
     *     
     */
    public void setTable(Table value) {
        this.table = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the linkPosition property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLinkPosition() {
        return linkPosition;
    }

    /**
     * Sets the value of the linkPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLinkPosition(BigDecimal value) {
        this.linkPosition = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the sensorIdOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorIdOriginal() {
        return sensorIdOriginal;
    }

    /**
     * Sets the value of the sensorIdOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorIdOriginal(String value) {
        this.sensorIdOriginal = value;
    }

    /**
     * Gets the value of the laneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLaneNumber() {
        return laneNumber;
    }

    /**
     * Sets the value of the laneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLaneNumber(BigInteger value) {
        this.laneNumber = value;
    }

    /**
     * Gets the value of the healthStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHealthStatus() {
        return healthStatus;
    }

    /**
     * Sets the value of the healthStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHealthStatus(BigDecimal value) {
        this.healthStatus = value;
    }

}
